# Generated by Django 3.2.7 on 2022-01-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_image', models.ImageField(blank=True, upload_to='photos/album')),
                ('background_video', models.FileField(upload_to='photos/albummedia')),
            ],
        ),
        migrations.CreateModel(
            name='MeetOurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='photos/album')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
    ]
