# Generated by Django 3.2.9 on 2022-03-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20220304_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundVideo',
        ),
    ]
